# Generated by Django 4.1.4 on 2022-12-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('Name', models.CharField(max_length=25, verbose_name='Имя')),
                ('Patronymic', models.CharField(max_length=25, verbose_name='Отчество')),
                ('Passport', models.CharField(max_length=11, verbose_name='Серия и номер пасспорта')),
                ('Date_of_Birth', models.DateField(verbose_name='Дата рождения')),
                ('Telephone', models.CharField(max_length=16, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_date', models.DateTimeField(verbose_name='Время проведения')),
                ('Event_place', models.CharField(max_length=50, verbose_name='Местро проведения')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Название отеля')),
                ('Class', models.CharField(max_length=30, verbose_name='Класс отеля')),
            ],
        ),
        migrations.CreateModel(
            name='TypeofTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, verbose_name='Тип тура')),
                ('Number_of_persons', models.IntegerField(verbose_name='Количество человек')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='Patronymic',
            field=models.CharField(default=1, max_length=25, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Название тура')),
                ('Departure', models.DateField(verbose_name='Отправление')),
                ('Arrival', models.DateField(verbose_name='Прибытие')),
                ('T_Events', models.ManyToManyField(to='events.events')),
                ('T_Hotels', models.ManyToManyField(to='events.hotels')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.typeoftour')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_sale', models.DateField(verbose_name='Дата продажи билета')),
                ('Price_of_sale', models.IntegerField(verbose_name='Цена билета')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.clients')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.employees')),
                ('Tours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.tours')),
            ],
        ),
    ]
