# Generated by Django 4.1.4 on 2022-12-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_clients_events_hotels_typeoftour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Name',
            field=models.CharField(default=1, max_length=60, verbose_name='Название мероприятия'),
            preserve_default=False,
        ),
    ]
